fixes:
  - "io/ballerina/stdlib/ai/plugin::.compiler-plugin/src/main/java/io/ballerina/stdlib/ai/plugin"
  - "ballerina/ai/**/::../ballerina/"

ignore:
  - "ballerina-tests"
  - "native/src/test"
  - "ballerina/modules/intelligence" # Generated connector
  - "ballerina/modules/observe" # Needs manual testing with observablity provider

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
