// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/log;

// Agent lifecycle logging

isolated function logAgentExecutionStarted(string executionId, string query, string sessionId) {
    log:printDebug("Agent execution started",
            executionId = executionId,
            query = query,
            sessionId = sessionId
    );
}

isolated function logAgentExecutionCompleted(string executionId, string steps, string answer) {
    log:printDebug("Agent execution completed successfully",
            executionId = executionId,
            steps = steps,
            answer = answer
    );
}

isolated function logAgentExecutionFailed(string executionId, string steps, Error err) {
    log:printDebug("Agent execution failed",
            err,
            executionId = executionId,
            steps = steps
    );
}

// Execution loop logging

isolated function logExecutionLoopStarted(string executionId, string sessionId, int maxIterations) {
    log:printDebug("Agent execution loop started",
            executionId = executionId,
            sessionId = sessionId,
            maxIterations = maxIterations
    );
}

isolated function logIterationStarted(string executionId, int iteration, int maxIterations,
        int stepsCompleted, string sessionId) {
    log:printDebug("Agent iteration started",
            executionId = executionId,
            iteration = iteration,
            maxIterations = maxIterations,
            stepsCompleted = stepsCompleted,
            sessionId = sessionId
    );
}

isolated function logLlmReasoningStarted(string executionId, string sessionId, string history) {
    log:printDebug("LLM reasoning started",
            executionId = executionId,
            sessionId = sessionId,
            history = history
    );
}

isolated function logIterationError(string executionId, string sessionId, Error err) {
    error? cause = err.cause();
    log:printDebug("Error occurred during agent iteration",
            err,
            executionId = executionId,
            sessionId = sessionId,
            cause = cause !is () ? cause.toString() : "none"
    );
}

isolated function logFinalAnswer(string executionId, string answer, string sessionId) {
    log:printDebug("Final answer generated by agent",
            executionId = executionId,
            answer = answer,
            sessionId = sessionId
    );
}

// LLM tool selection logging

isolated function logToolSelectionRequest(string executionId, string sessionId,
        string messages, string availableTools) {
    log:printDebug("Requesting tool selection from LLM",
            executionId = executionId,
            sessionId = sessionId,
            messages = messages,
            availableTools = availableTools
    );
}

isolated function logToolsSelected(string executionId, string sessionId, FunctionCall[] tools) {
    log:printDebug("LLM selected tools",
            executionId = executionId,
            sessionId = sessionId,
            tools = tools
    );
}

isolated function logChatResponse(string executionId, string sessionId, string? response) {
    log:printDebug("LLM provided chat response instead of tool call",
            executionId = executionId,
            sessionId = sessionId,
            response = response
    );
}

// Tool execution logging

isolated function logToolCallParsed(string executionId, string sessionId,
        string toolName, map<json>? arguments) {
    log:printDebug("Parsed LLM response as tool call",
            executionId = executionId,
            sessionId = sessionId,
            toolName = toolName,
            arguments = arguments
    );
}

isolated function logToolExecutionError(string executionId, string observation,
        string sessionId, string toolName) {
    log:printDebug("Tool execution resulted in error",
            executionId = executionId,
            observation = observation,
            sessionId = sessionId,
            toolName = toolName
    );
}

isolated function logToolExecutionSuccess(string executionId, string sessionId,
        string toolName, anydata|error output) {
    log:printDebug("Tool execution successful",
            executionId = executionId,
            sessionId = sessionId,
            toolName = toolName,
            output = output is error ? output.toString() : output
    );
}

// Memory logging

isolated function logMemoryRetrievalFailed(string executionId, string sessionId, MemoryError err) {
    log:printDebug("Failed to retrieve conversation history from memory",
            err,
            executionId = executionId,
            sessionId = sessionId
    );
}

isolated function logMemoryUpdateFailed(MemoryError err) {
    log:printError("Error occurred while updating the memory", err);
}

isolated function logMemoryDeleteFailed(MemoryError err) {
    log:printError("Error occurred while deleting stateless memory", err);
}
