// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Represent the execution result of a tool.
public type ToolExecutionResult record {|
    # Return value of the tool
    any|error result;
|};

# Executes an AgentTool.
#
# + tool - Function pointer to the AgentTool
# + llmToolInput - Tool input generated by the LLM
# + context - Additional context for the tool execution
# + return - Result of the tool execution
public isolated function executeTool(FunctionTool tool, map<json> llmToolInput, Context context = new)
    returns ToolExecutionResult {
    (anydata|Context)[]|error inputArgs = getInputArgumentsOfTool(tool, llmToolInput, context);
    if inputArgs is error {
        return {result: inputArgs};
    }
    any|error result = function:call(tool, ...inputArgs);
    return {result};
}

# Resolves function parameter types and builds the argument list for tool execution.
#
# + tool - The function tool to get arguments for
# + inputValues - The input values from the LLM
# + context - Additional context for the tool execution
# + return - An ordered array of arguments or an error
isolated function getInputArgumentsOfTool(FunctionTool tool, map<json> inputValues, Context context = new)
    returns (anydata|Context)[]|error {
    map<anydata> inputArgs = {};
    boolean hasContextArg = false;
    map<typedesc<anydata|Context>> typedescs = getToolParameterTypes(tool);
    foreach [string, typedesc<anydata|Context>] [parameterName, typedescriptor] in typedescs.entries() {
        if (inputValues.hasKey(parameterName) && typedescriptor is typedesc<anydata> && !isContextType(typedescriptor)) {
            anydata inputArg = check inputValues.get(parameterName).cloneWithType(typedescriptor);
            inputArgs[parameterName] = inputArg;
        } else if isContextType(typedescriptor) {
            hasContextArg = true;
        }
    }

    map<anydata> argsWithDefaultValues = (check trap getArgsWithDefaultsExcludingContext(tool, inputArgs));
    anydata[] orderedArgs = argsWithDefaultValues.toArray();
    if (!hasContextArg) {
        return orderedArgs.cloneReadOnly();
    }
    // Compiler plugin guarantees context is the first argument, if present
    return [context, ...orderedArgs.cloneReadOnly()];
}

# Converts raw tool output to a ToolOutput or appropriate error type.
# Handles http:Response, stream, anydata, and error outputs.
#
# + rawObservation - The raw output from tool execution
# + toolName - The name of the tool that produced the output
# + inputValues - The input values used for execution
# + variables - The tool's variable schema (for error messages)
# + return - A ToolOutput or an appropriate error
isolated function convertToolOutput(any|error rawObservation, string toolName, map<json> inputValues,
        map<json>? variables) returns ToolOutput|ToolExecutionError|LlmInvalidGenerationError {
    any|error observation = rawObservation;
    if observation is http:Response {
        observation = observation.getStatusCodeRecord();
    }
    if observation is stream<anydata, error?> {
        anydata[]|error result = from anydata item in observation
            select item;
        observation = result;
    }
    if observation is anydata {
        logToolSucceeded(toolName, observation.toString());
        return {value: observation};
    }
    if observation !is error {
        logToolInvalidOutput((typeof observation).toString(), toolName, inputValues.length() == 0 ? {} : inputValues);
        return error ToolInvalidOutputError("Tool returns an invalid output. Expected anydata or error.",
            outputType = typeof observation, toolName = toolName, inputs = inputValues.length() == 0 ? {} : inputValues);
    }
    if observation.message() == "{ballerina/lang.function}IncompatibleArguments" {
        string instruction = string `Tool "${toolName}"  execution failed due to invalid inputs provided.`
            + string ` Use the schema to provide inputs: ${variables.toString()}`;
        logToolIncompatibleArguments(instruction, toolName, inputValues.length() == 0 ? {} : inputValues);
        return error ToolInvalidInputError("Tool is provided with invalid inputs.",
            observation, toolName = toolName, inputs = inputValues.length() == 0 ? {} : inputValues,
            instruction = instruction);
    }
    return {value: observation};
}
